### ISSUE TITLE
Does not work on 1903

### ISSUE THREAD

**Issue by nraggett** [Triplesalt/WMRSensors#4]
After injecting the DLL no pipe is found.

**Comment by nraggett** [comment]
Looks like I'm running on this driver version: 10.0.18362.1062

**Comment by Triplesalt** [comment]
On my end, it appears to work on the same driver and shows the camera images. Other sensor data does not work for 1903 at the moment, I'll look into it.

You could try injecting the dll to any other 64bit application, such as notepad. It should at least connect and show errors (since it can't find the driver). Also check if the dll actually appears in the module list if you select properties in Process Hacker.

**Comment by nraggett** [comment]
The DLL seems to work with Notepad, showing: 
`Connecting to pipe server... Connected
Host log : ERROR: Can't find MRUSBHost.dll!
Host log : Camera hooks are disabled.
Host log : ERROR: Can't find MotionControllerHid.dll!
Host log : Controller hooks are disabled.`
However it does not load into the WUDFHost.exe process, the details of the WUDFHost.exe are:
Command Line: 
`"C:\Windows\System32\WUDFHost.exe" -HostGUID:{193a1820-d9ac-4997-8c55-be817523f6aa} -IoEventPortName:\UMDFCommunicationPorts\WUDF\HostProcess-9ede12fd-acc5-4ff6-a79f-88942854e9a8 -SystemEventPortName:\UMDFCommunicationPorts\WUDF\HostProcess-9ead4b73-bc25-4218-9500-3f3ca135c09c -IoCancelEventPortName:\UMDFCommunicationPorts\WUDF\HostProcess-cbfaf46e-8ce7-4bd8-b42a-c416fd3189c5 -NonStateChangingEventPortName:\UMDFCommunicationPorts\WUDF\HostProcess-49a854d0-9532-4aeb-a55e-2576fde4a767 -LifetimeId:2687c22a-cd4a-440f-991e-a67326b18bf2 -DeviceGroupId: -HostArg:0`
Current Directory: 
`C:\WINDOWS\System32\DriverStore\FileRepository\hololenssensors.inf_amd64_21a2d80ddbab47f3\`

Process Hacker is started as Admin and successfully injects the DLL into notepad, so this seems to be an issue with WUDFHost.
I'm currently running Windows 10 1903 Build 18362.10005 with a Samsung Odyssey (original, not plus)

**Comment by nraggett** [comment]
Update: Just got the DLL to inject and got a working camera stream. 

The WUDFHost.exe was run with the Local Services account, which seems to only have access permissions to the `C:\Windows\System32` directory. As such just copy-pasting the DLL into that directory allowed me to inject it into WUDFHost.exe and get camera frames.

**Comment by nraggett** [comment]
Update: Just got the DLL to inject and got a working camera stream. 

The WUDFHost.exe was run with the Local Services account, which seems to only have access permissions to the `C:\Windows\System32` directory. As such just copy-pasting the DLL into that directory allowed me to inject it into WUDFHost.exe and get camera frames.

**Comment by Triplesalt** [comment]
Thanks a lot! I have the project on another hard drive without access restrictions and therefore didn't notice.

I have updated the Readme instructions.
